language: python
python:
  - 3.4
  - 3.5
matrix:
  fast_finish: true
sudo: false
cache: pip
install:
  - pip install coveralls
  - pip install flake8==2.4.1
  - pip install pep257==0.5.0
  - npm install -g eslint@1.1.0
  - gem install rubocop -v 0.50
  - gem install scss_lint -v 0.43.2
script:
  - flake8
  - pep257
  - coverage run --source=farcy setup.py test
after_success: coveralls
