"""Helper methods and classes."""


from collections import defaultdict
try:
    from configparser import ConfigParser  # PY3
except ImportError:
    from ConfigParser import SafeConfigParser as ConfigParser  # PY2
from datetime import timedelta, tzinfo
import logging
import os
from .const import FARCY_COMMENT_START, NUMBER_RE, CONFIG_DIR
from .exceptions import FarcyException

IS_FARCY_COMMENT = FARCY_COMMENT_START.split('v')[0]


def added_lines(patch):
    """Return a mapping of added line numbers to the patch line numbers."""
    added = {}
    lineno = None
    position = 0
    for line in patch.split('\n'):
        if line.startswith('@@'):
            lineno = int(NUMBER_RE.match(line.split('+')[1]).group(1))
        elif line.startswith(' '):
            lineno += 1
        elif line.startswith('+'):
            added[lineno] = position
            lineno += 1
        elif line == "\ No newline at end of file":
            continue
        else:
            assert line.startswith('-')
        position += 1
    return added


def extract_issues(text):
    """Extract farcy violations from a text."""
    if not is_farcy_comment(text):
        return []
    # Strip out start of bullet point, ignore first line
    return [line[2:] for line in text.split('\n')[1:]]


def filter_comments_from_farcy(comments):
    """Filter comments for farcy comments."""
    return (comment for comment in comments if is_farcy_comment(comment.body))


def filter_comments_by_path(comments, path):
    """Filter a comments iterable by a file path."""
    return (comment for comment in comments if comment.path == path)


def is_farcy_comment(text):
    """Return boolean if text was generated by Farcy."""
    return text.startswith(IS_FARCY_COMMENT)


def issues_by_line(comments, path):
    """Return dictionary mapping patch line nr to list of issues for a path."""
    by_line = defaultdict(list)
    for comment in filter_comments_by_path(comments, path):
        issues = extract_issues(comment.body)
        if issues:
            by_line[comment.position].extend(issues)
    return by_line


def plural(items, word):
    """Return number of items followed by the right form  of ``word``.

    ``items`` can either be an int or an object whose cardinality can be
    discovered via `len(items)`.

    The plural of ``word`` is assumed to be made by adding an ``s``.

    """
    item_count = items if isinstance(items, int) else len(items)
    word = word if item_count == 1 else word + 's'
    return '{0} {1}'.format(item_count, word)


def process_user_list(user_list):
    """Return a normalized set from an expansion of the user list.

    A single item in the input list can contain a comma separated list of items
    which will be expanded in the output set.

    Each item will be normalized to its lowercase format for comparison.

    """
    users = []
    for item in user_list:
        users.extend(x.strip().lower() for x in item.split(','))
    return set(users) if users else None


def split_dict(data, keys):
    """Split a dict in a dict with keys `keys` and one with the rest."""
    with_keys = {}
    without_keys = {}
    for key, value in data.items():
        if key in keys:
            with_keys[key] = value
        else:
            without_keys[key] = value
    return with_keys, without_keys


def subtract_issues_by_line(by_line, by_line2):
    """Return a dict with all issues in by_line that are not in by_line2."""
    result = {}
    for key, values in by_line.items():
        exclude = by_line2.get(key, [])
        filtered = [value for value in values if value not in exclude]
        if filtered:
            result[key] = filtered
    return result


class Config(object):

    """Holds configuration for Farcy."""

    def __init__(self, repository=None):
        """Initialize a config with default values."""
        self.repository = repository
        self.start_event = None
        self.debug = False
        self.exclude_paths = []
        self.limit_users = None
        self.log_level = 'NOTSET'
        self.pr_issue_report_limit = 128

        self._dirty = set()
        self._config_path = os.path.join(CONFIG_DIR, 'farcy.conf')

    def load_config_file(self):
        """
        Load default values from configuration values.

        Will not overwrite any value if already set.
        """
        if not os.path.isfile(self._config_path):
            return

        allowed = ('start_event', 'debug', 'exclude_paths', 'limit_users',
                   'log_level', 'pr_issue_report_limit')

        config_file = ConfigParser()
        config_file.read(self._config_path)
        if self.repository is None and config_file.has_option(
                'default', 'repository'):
            self.repository = config_file.get('default', 'repository')

        for section in (self.repository, 'default'):
            if not config_file.has_section(section):
                continue
            for attr, cur_value in self.__dict__.items():
                if not config_file.has_option(section, attr) or \
                   attr not in allowed:
                    continue
                value = config_file.get(section, attr)
                if attr == 'limit_users':
                    value = process_user_list([value])
                elif attr == 'exclude_paths':
                    value = [item.strip() for item in value.split(',')]
                elif attr == 'debug':
                    value = value.lower() in ('true', '1')
                elif attr in ('start_event', 'pr_issue_report_limit'):
                    value = int(value)
                setattr(self, attr, value)

    def load_dict(self, values):
        """Load values from a dict."""
        for attr, value in values.items():
            setattr(self, attr, value)

    @property
    def log_level_int(self):
        """Int value of the log level"""
        return getattr(logging, self.log_level)

    def user_whitelisted(self, user):
        """Return if user is whitelisted."""
        return self.limit_users is None or user.lower() in self.limit_users

    def __setattr__(self, attr, value):
        """
        Set new config attribute.

        Validates new attribute values and tracks if changed from default.
        """
        if attr in self.__dict__ and self.__dict__[attr] == value:
            return
        elif attr == 'debug' and value:
            self.__dict__['log_level'] = 'DEBUG'
        elif attr == 'log_level' and self.debug:
            return
        elif attr == 'log_level' and value is not None:
            value = value.upper()
            if value not in ('CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG',
                             'NOTSET'):
                raise FarcyException('Invalid log level specified: {0}'.format(
                    value))
        elif attr == 'repository' and value is not None:
            repo_parts = value.split('/')
            if len(repo_parts) != 2:
                raise FarcyException(
                    'Invalid repository specified: {0}'.format(value))

        if attr in self.__dict__:
            self._dirty.add(attr)
        self.__dict__[attr] = value

    def __repr__(self):
        """String representation of the config."""
        return '<Config {0}>'.format(self.__dict__)


class UTC(tzinfo):

    """Provides a simple UTC timezone class.

    Source: http://docs.python.org/release/2.4.2/lib/datetime-tzinfo.html

    """

    dst = lambda x, y: timedelta(0)
    tzname = lambda x, y: 'UTC'
    utcoffset = lambda x, y: timedelta(0)
